### ISSUE TITLE
Base box for LXC does no longer work with newer kernels

### ISSUE THREAD

**Issue by SvenBrunk** [OXID-eSales/oxvm_eshop#12]
fuse is no longer loaded as module in newer kernels. the base box for LXC needs to be updated

**Comment by rezonanc-oxid** [comment]
Will be discussed with our PO in terms of when this is needed to be done.

**Comment by rezonanc-oxid** [comment]
Issue has been fixed, feel free to check the commits:
* https://github.com/OXID-eSales/oxvm_eshop/commit/cba519dfcc2bb80f0bc351d08e433ebe3bdae7b7
* https://github.com/OXID-eSales/oxvm_base/commit/bec4f0ae94e54483ec7957043b838e36667adc94
