### ISSUE TITLE
documentation for Zend Guard Loader does not take into account phpbrew

### ISSUE THREAD

**Issue by SvenBrunk** [OXID-eSales/oxvm_eshop#13]
when using a different php version in your personal.yml file, the Zend Guard extension needs to go to a different directory

**Comment by rezonanc-oxid** [comment]
If we would note this inside our documentation would it help? Or would you suggest to somehow automate this? Any other possible way to solve this?

**Comment by SvenBrunk** [comment]
actually I think Gregor (now new on shop team :) ) already had a fully automatted ansible role for installing it. Maybe this part can be integrated there easily. But the documentation would need to be updated anyway. Either by removing the manual part or by adding the hints about the phpbrew parts.

Von: Edvinas Aleksejonokas [mailto:notifications@github.com]
Gesendet: Mittwoch, 16. März 2016 15:33
An: OXID-eSales/oxvm_eshop
Cc: Sven Brunk
Betreff: Re: [oxvm_eshop] documentation for Zend Guard Loader does not take into account phpbrew (#13)


If we would note this inside our documentation would it help? Or would you suggest to somehow automate this? Any other possible way to solve this?

**Comment by rezonanc-oxid** [comment]
Zend Guard role was integrated, documentation has been updated: https://github.com/OXID-eSales/oxvm_eshop/commit/621564b033c9fc9e99b23ae701fee84eea2bb60e
