### ISSUE TITLE
The personal yml is really harsh about errors.

### ISSUE THREAD

**Issue by sebbbbauer** [OXID-eSales/oxvm_eshop#14]
If you leave an entry empty, e.g. "mysql:" without any further instructions, you get a vagrant error like this:
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'NoneType': ...

Therefore it would be nice, to have a more resistent version (if there is nothing in the entry, don't work further - leave the defaults in it) or have a self/personal.yml checker in the playbook.

**Comment by rezonanc-oxid** [comment]
I would suggest to note this in our documentation unless there is an easy way to write a `personal.yml` file validator?
In both cases can we convert this to a PR? Or should we just update the documentation that one must be  careful with filling in `personal.yml`?
