### ISSUE TITLE
The oxid database user can not set the transaction isolation level

### ISSUE THREAD

**Issue by sebbbbauer** [OXID-eSales/oxvm_eshop#15]
In the oxLegacyDb is a method 'setTransactionIsolationLevel', which sets the transaction isolation level. While introducing doctrine we wrote a test for it. The test isn't running, cause the transaction isolation level could not be set.

Try 'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED' and read the value. It will stay at the previous value.

**Comment by keywan-ghadami** [comment]
How is that related to the oxvm? Did you start the transaction before?

**Comment by sebbbbauer** [comment]
@keywan: no, the test for transaction isolation level didn't started a transaction before setting the isolation level. 

The doctrine dbal calls internal the sql set global. We solved the issue with this test by setting it through sql and set session. We can close this one therefore.
