### ISSUE TITLE
The database isn't reachable from outside

### ISSUE THREAD

**Issue by sebbbbauer** [OXID-eSales/oxvm_eshop#16]
The database could be reachable from the outside (with MySQL Workbench). This would be a nice, time saving feature.

**Comment by rezonanc-oxid** [comment]
Can the addition for adminer/adminer_editor be a possible substitution for this? https://github.com/OXID-eSales/oxvm_eshop/commit/0bf1c231429ef4c11161dce394c61e13f514fdc6

**Comment by sebbbbauer** [comment]
I've found the way to get it running in MySQL Workbench. Over 'Standard TCP/IP over SSH' it's possible to connect to the database from the outside. I suppose there is a shell way analog to this. If the implementation and maintenance of adminer is no big effort, it would be a nice to have, cause it will reduce the settling-in period for new developers or non developmer users.

**Comment by rezonanc-oxid** [comment]
Since a workaround has been found and adminer (https://github.com/OXID-eSales/oxvm_eshop/commit/0bf1c231429ef4c11161dce394c61e13f514fdc6) integration is present I feel safe to close the issue.
