### ISSUE TITLE
runtests not working on clean install

### ISSUE THREAD

**Issue by nymo** [OXID-eSales/oxvm_eshop#20]
I did a clean install and tried to run the testsuite. The result is that nothing happens. I just get the following output on the console:

`vagrant@oxideshop:/var/www/oxideshop/source/vendor/bin$ ./runtests

dir=$(d=${0%[/\]*}; cd "$d"; cd '../phpunit/phpunit' && pwd)
# See if we are running in Cygwin by checking for cygpath program

if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/\* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpunit" "$@"
vagrant@oxideshop:/var/www/oxideshop/source/vendor/bin$
`

Tested on Win10

**Comment by rezonanc-oxid** [comment]
Hi,

Sorry for late answer. This appears to be a bug of composer, which detects the presence of cygwin and tries to write cygwin compatible scripts.

AFAIK this should not be present any more. Is there still an issue with this?

**Comment by nymo** [comment]
@rezonanc-oxid 
thanks for your answer. I did a clean reinstall and tried it again. Now the runtests are working as expected.
