### ISSUE TITLE
Flow theme is activated but not installed

### ISSUE THREAD

**Issue by hendrikfreytag** [OXID-eSales/oxvm_eshop#21]
I changed nothing and started the oxvm. After installation I got an error that some templates are not found. I checked that and found out that flow theme is activated but there is no flow theme installed in the shop. So it tried to find flow theme templates which are not present.

**Comment by rezonanc-oxid** [comment]
A solution is provided at https://github.com/OXID-eSales/oxvm_eshop/issues/23.
