### ISSUE TITLE
Enable xdebug for phpbrewed php version

### ISSUE THREAD

**Issue by robertblank** [OXID-eSales/oxvm_eshop#24]
Hello,

at the moment to enable xedbug in a "phpbrewed" php version, the only solution I found was executing a command in the VM console

```
phpbrew switch php-5.3.29
phpbrew ext enable xdebug
phpbrew list-ini  # to see if ini file was loaded and where it lives
sudo service apache2 restart
```

If would be a nice feature to be able to have this by default

**Comment by Sieg** [comment]
As phpbrew and phpswitch was removed due to unstable results, this question is not viable anymore. Xdebug is now activated correctly for installed php versions.
