### ISSUE TITLE
Varnish is not able to be activated

### ISSUE THREAD

**Issue by tjschneider** [OXID-eSales/oxvm_eshop#25]
Hi,

if I set varnish install option in my personal.yml to true, provisioning is not possible. It seems there is some problem with the "md5" to compare file changes.

==> default: TASK [varnish : Trigger default Varnish configuration validation] **************
==> default: fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'not varnish_candidate_config_result|skipped and (\n  not varnish_current_config_result.stat.exists\n  or\n  varnish_current_config_result.stat.md5 != varnish_candidate_config_result.stat.md5\n)\n' failed. The error was: error while evaluating conditional (not varnish_candidate_config_result|skipped and (\n  not varnish_current_config_result.stat.exists\n  or\n  varnish_current_config_result.stat.md5 != varnish_candidate_config_result.stat.md5\n)\n): 'dict object' has no attribute 'md5'\n\nThe error appears to have been in '/vagrant/base_vm/ansible/roles/varnish/tasks/install.yml': line 47, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Trigger default Varnish configuration validation\n  ^ here\n“}

**Comment by floeschie** [comment]
Hi Thorsten, thanks for the info, we'll have a look at it hopefully very soon.

**Comment by stasiukaitis-saulius** [comment]
Hi Thorsten @tjschneider ,

Sounds like you did not add configuration for Varnish. The Configuration should be placed in path_to_oxid_eshop/library/ReverseProxy/Varnish 

library directory is at the same level  as source.
Varnish directory contains of configuration for Varnish: default.vcl and servers_conf.vcl.varnish_4.dist You could get the content for the directory from one of OXID repositories. For that you would need an access, but Florian already gave you a hint how to get it :)

**Comment by rezonanc-oxid** [comment]
I've added information about this in our troubleshooting section: https://github.com/OXID-eSales/oxvm_eshop/blob/master/README.rst#trigger-default-varnish-configuration-validation-task-fails

Can we agree to close the issue?

**Comment by tjschneider** [comment]
Hi Edvinas,
thanks for the troubleshoot entry. I will check the process as "user zero" :-) 
Please let this issue open until I can give a positive feedback... Is this ok for you?

**Comment by rezonanc-oxid** [comment]
Yes, that's more than ok!
Have you already got access to our Varnish configuration? Do you need any assistance with it?

**Comment by rezonanc-oxid** [comment]
Hi Thorsten,

Any news about varnish configuration issue?

**Comment by tjschneider** [comment]
I got it running yesterday and already talked to Marco about the process. The FAQ has to be changed as the process and the steps to take are a bit more complicated as only sending a mail. Is it helpful if I send you a draft after I clarified the steps with Marco?

**Comment by rezonanc-oxid** [comment]
If you are already in communication with Marco, just send him the draft, I'll extract that from him :) and make the necessary changes. I'll close this issue when the action will be taken from my side.

**Comment by kermie** [comment]
> I figure @kermie can help you getting onboarded into the PE/EE contribution process, so that you get access to our private repositories.

@floeschie That didn't help in this case as the varnish config files can be found in EE documentation.

>  I've added information about this in our troubleshooting section: https://github.com/OXID-eSales/oxvm_eshop/blob/master/README.rst#trigger-default-varnish-configuration-validation-task-fails

@rezonanc-oxid Can you please correct this section? The varnish configuration files can be downloaded from the EE documentation. Those who don't have access might apply for it filling the form on this page: https://www.oxid-esales.com/de/support-services/dokumentation-und-hilfe/oxid-eshop/enterprise-edition.html; ee-pe-repo@ has got nothing to do with it ;)

I reckon we can close this issue after that if @tjschneider agrees.

Cheers!

**Comment by rezonanc-oxid** [comment]
There has been a massive update regarding Varnish activation within a VM:

* There is a dedicated package from a private repository for Varnish configuration files
* Readme has been updated with instructions on how to use this repository inside the VM

More information could be found here: https://github.com/OXID-eSales/oxvm_eshop#trigger-varnish-installation

Given the amount of time there was no response for the issue I'm closing this ATM. Feel free to re-open it incase there are any problems with Varnish and VM.
