### ISSUE TITLE
"zlib_decode(): data error" after running "vagrant up"

### ISSUE THREAD

**Issue by cesnauskast** [OXID-eSales/oxvm_eshop#29]
I just tried to install the newest OXID eshop version according to guidelines provided here: https://github.com/OXID-eSales/oxvm_eshop#quick-start

After running `vagrant up` under "Run composer install in repository root" task I got fatal error: 
"Loading composer repositories with package information\nUpdating dependencies (including require-dev)\nFailed to decode response: zlib_decode(): data error\nRetrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info"

**Comment by cesnauskast** [comment]
By the way, I'm using Windows, vagrant version = 1.8.7, virtualbox version = 5.1.8

After looking through a lot of possible fixes I found the solution. This issue appeared, because of virtualbox. Problem is gone after downgrading virtualbox to 5.1.6 version.
For more information please go here:
https://github.com/composer/composer/issues/5814#issue-185163914

**Comment by rezonanc-oxid** [comment]
Thanks! We'll keep this information as reference in case someone else stumbles upon this problem.

**Comment by rezonanc-oxid** [comment]
I can confirm that it also works with Virtualbox 5.1.10 version. And indeed 5.1.8 has problems (platform independent).
