### ISSUE TITLE
runmetrics gives 2520 lines of notices

### ISSUE THREAD

**Issue by hendrikfreytag** [OXID-eSales/oxvm_eshop#3]
Only thing I changed: UTF8 on, set Github token

I started to vagrant machine, logged in with ssh and started ./runmetrics in /var/www/oxideshop/source/vendor/bin. I get 2520 lines of notices:

After:
>Generating pdepend log files, this may take a moment.
>Time: 06:54; Memory: 220.75Mb

The following lines are repeated 280 times:

>PHP Notice:  Undefined index: stat in /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php on line 582
>PHP Stack trace:
>PHP   1. {main}() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php:0
>PHP Notice:  Undefined index: stat in /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php on line 584
>PHP Stack trace:
>PHP   1. {main}() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php:0
>PHP Notice:  Undefined index: stat in /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php on line 586
>PHP Stack trace:
>PHP   1. {main}() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/MC_Metrics.php:0

**Comment by rezonanc-oxid** [comment]
Thanks for the notice!

I've forwarded this issue to: https://github.com/OXID-eSales/testing_library/issues/2 as it is directly related to our testing library SDK component.

It seems that it's easy to fix this as we only need to double check if key exists inside the array. We hope to notify about the fix soon.

**Comment by rezonanc-oxid** [comment]
The issue was fixed in https://github.com/OXID-eSales/testing_library/issues/2.

I've double checked this against our CE repository `b-dev-ce` branch and `v4.9.5` tag. No notices were thrown.
