### ISSUE TITLE
Third party network problems

### ISSUE THREAD

**Issue by sebbbbauer** [OXID-eSales/oxvm_eshop#31]
From time to time some of the roles (or some subtasks of the roles) fail with 404s or other issues.

For example the fixed firefox version (which normally works) fails sometimes with this message:
==> default: fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for kent.dl.sourceforge.net:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by rezonanc-oxid** [comment]
This is something that we don't have much control of. What we can do is try to change the mirrors which are being used. For firefox and selenium packages I've changed the mirror to our VM assets repository. I hope this will be more reliable and stable. 

Link to change: https://github.com/OXID-eSales/oxvm_eshop/commit/8f289ebf9af9b8497b2f1838ec91d20fae79f0f0
