### ISSUE TITLE
oxid EE 6 beta Installation (resolved)

### ISSUE THREAD

**Issue by ssemiz** [OXID-eSales/oxvm_eshop#33]
Preconditions: 
- Windows 10, 
- VirtualBox 5.1.6, 
- Vagrant 1.8.6
- Ubuntu 16.04 box made with packer (some php 7 modules installed on top)

Installation step 4 to 5 (Database) abortet with this alert:

**FEHLER: (Tabellen)Probleme mit folgenden SQL Befehlen: ( DELETE FROM `oxrolefields` WHERE OXNAME IN ( 'TOBASKET', 'SHOWLONGDESCRIPTION', 'SHOWARTICLEPRICE', 'SHOWSHORTDESCRIPTION'); ): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'oxid.oxrolefields' doesn't exist** 

It's an Windows issue with symliks that only works under admin privileges.

At first I've turn off all VM's down (vagrant halt), then started VirtualBox as admin (and closed it after that),
and than I've started the vm again. Voilá, intallation of oxid EE beta 6 passed successfully.

I hope, this will be helpfull

**Comment by rezonanc-oxid** [comment]
Just to double-check, this is not directly related to `oxvm_eshop` repository as other VM solution was used at this point, correct?

What I can relate to this are the following issues:
* #29 - VirtualBox version problem 
* #32 - VirtualBox/Windows symlink problem

The mentioned issues are referenced in our `oxvm_eshop` repository `README.rst` document "getting started"/"dependencies" section.

Could you agree that we can treat this as duplicate and mark this as issue solved?

**Comment by ssemiz** [comment]
Hi Aleksejonkas,that's right, this is not related to oxvm_repository, und yes it's resolved as I've wrote in subject, butit's eventualy helpfull for all that using an other vm then oxvm_eshop. You can do anything you want with this post ;-)Best regards---------- UrsprEdvinas Aleksejonokas <notifications@github.com> hat am 16. Dezember 2016 um 16:04 geschrieben:Just to double-check, this is not directly related to oxvm_eshop repository as other VM solution was used at this point, correct?What I can relate to this are the following issues:#29 - VirtualBox version problem#32 - VirtualBox/Windows symlink problemThe mentioned issues are referenced in our oxvm_eshop repository README.rst document "getting started"/"dependencies" section.Could you agree that we can treat this as duplicate and mark this as issue solved?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rezonanc-oxid** [comment]
Thanks for confirmation!

**Comment by tc-steffen** [comment]
mh... strange, I got the same error message on CentOS now... not windows. Any idea?

**Comment by rezonanc-oxid** [comment]
Just to double check, by stating CentOS you mean that your host machine is CentOS and you are using VirtualBox for VM?

**Comment by tc-steffen** [comment]
ah, no, I was actualy trying to simply install the OXID eShop on a stand-alone CentOS server.... no virtualization at all.

**Comment by rezonanc-oxid** [comment]
Could you please provide output from `ls -l /var/www/oxideshop/vendor/bin` and `which 'readlink'` commands? (adjust `/var/www/oxideshop` to the root path of eShop project folder, the one which has `vendor` folder inside it)

**Comment by rezonanc-oxid** [comment]
Seems the issue was misplaced `vendor` folder. More details can be found at https://github.com/OXID-eSales/oxideshop_ee/issues/14.
