### ISSUE TITLE
Switch away from .dev TLD

### ISSUE THREAD

**Issue by flow-control** [OXID-eSales/oxvm_eshop#34]
Hi there,

as you may not already know, the `.dev` TLD is taken [by Google](https://icannwiki.com/.dev) and therefore we should stop using it. There are a bunch of TLD's registered for cases like this, `.test` for example or maybe `.localhost`.

Kind regards

Flo

**Comment by alfredbez** [comment]
see also #4

**Comment by rezonanc-oxid** [comment]
Closing this one as it's a duplicate of #4.
