### ISSUE TITLE
Script "oe-eshop-db_migrate" was not found. Possible candidates:

### ISSUE THREAD

**Issue by KatoPue** [OXID-eSales/oxvm_eshop#37]
Pre-conditions:
OS: Windows 7
VirtualBox 5.1.18
Vagrant 1.8.5

running the command
`user@box:~/shared_folder/oxidBeta$ VERBOSE=1 vendor/bin/oe-eshop-facts oe-eshop-db_migrate`
does output the following:

```
Variables from: “oe-eshop-facts”
ESHOP_PHP_BIN_PATH: /home/vagrant/phpfarm/inst/current-bin/php
ESHOP_FACT_BIN_PATH: /home/vagrant/shared_folder/oxidBeta/vendor/oxid-esales/eshop-facts/oe-eshop-facts
ESHOP_FACT_BASEDIR: /home/vagrant/shared_folder/oxidBeta/vendor/oxid-esales/eshop-facts
ESHOP_SOURCE_PATH:
ESHOP_BOOTSTRAP_PATH:
ESHOP_CONFIG_PATH:
ESHOP_VENDOR_PATH:
ESHOP_VENDOR_BIN_PATH: /bin
ESHOP_VENDOR_NAME: oxid-esales
ESHOP_OXID_VENDOR_PATH:

Script “oe-eshop-db_migrate” was not found. Possible candidates:
```
The path to the `vendor/bin` folder could not be determined correctly.

I did a little bit of digging.
File: `oe-eshop-facts`
The variable `ESHOP_SOURCE_PATH` consits of `ESHOP_FACT_BASEDIR` and the `SOURCE_PATH_SUFFIX`.
Which translates to the path
`/home/vagrant/shared_folder/oxidBeta/vendor/oxid-esales/eshop-facts/../../source/`

Needless to say, it does not exist.
Could there be something wrong with the `SOURCE_PATH_SUFFIX` variable?
In fact `/home/vagrant/shared_folder/oxidBeta/vendor/oxid-esales/eshop-facts/../../../source/` does exist.

#32 did not solve the issue

**Comment by KristianH** [comment]
there is a similar/same ticket in bug tracking system too:
[6616](https://bugs.oxid-esales.com/view.php?id=6616)

**Comment by rezonanc-oxid** [comment]
If we would check the output on the VM with default configuration, we would see the results like this:

```
vagrant@oxideshop:/var/www/oxideshop$ VERBOSE=1 vendor/bin/oe-eshop-facts
Variables from: "oe-eshop-facts"
	ESHOP_PHP_BIN_PATH: /usr/bin/php
	ESHOP_FACT_BIN_PATH: /var/www/oxideshop/vendor/oxid-esales/eshop-facts/oe-eshop-facts
	ESHOP_FACT_BASEDIR: /var/www/oxideshop/vendor/bin
	ESHOP_SOURCE_PATH: /var/www/oxideshop/source
	ESHOP_BOOTSTRAP_PATH: /var/www/oxideshop/source/bootstrap.php
	ESHOP_CONFIG_PATH: /var/www/oxideshop/source/config.inc.php
	ESHOP_VENDOR_PATH: /var/www/oxideshop/vendor
	ESHOP_VENDOR_BIN_PATH: /var/www/oxideshop/vendor/bin
	ESHOP_VENDOR_NAME: oxid-esales
	ESHOP_OXID_VENDOR_PATH: /var/www/oxideshop/vendor/oxid-esales
```

Notice the value of `ESHOP_FACT_BASEDIR` which points to  `/var/www/oxideshop/vendor/bin` and if we would add `/../../source/` we would get `/var/www/oxideshop/vendor/bin/../../source/` which translates to `/var/www/oxideshop/source` - a valid path for the source of OXID eShop core.

I've noticed that in your case the value of `ESHOP_FACT_BASEDIR` points to a totally different point `/home/vagrant/shared_folder/oxidBeta/vendor/oxid-esales/eshop-facts` which usually is a symptom of lack of symlinks. Just to verify this could you please paste the results of the following command:

`/home/vagrant/shared_folder/oxidBeta/vendor/bin/` ?

The output (positive) should contain symlinks like in the following example:

```
vagrant@oxideshop:/var/www/oxideshop$ ls -l vendor/bin
total 112
lrwxrwxrwx 1 vagrant vagrant 34 Mar 27 12:49 doctrine-dbal -> ../doctrine/dbal/bin/doctrine-dbal
lrwxrwxrwx 1 vagrant vagrant 46 Mar 27 12:49 doctrine-migrations -> ../doctrine/migrations/bin/doctrine-migrations
...
```

**Comment by rezonanc-oxid** [comment]
Regarding the https://bugs.oxid-esales.com/view.php?id=6616 it's a bit different problem (unable to detect PHP executable), further actions needed are described in the ticket.

**Comment by KatoPue** [comment]
I did some more testing.
The symlinks are working, if vagrant is upped (`$ vagrant up`) fom an console with administrator privileges and the composer installation is run from the guest OS.

So it is not possible to create a new shop project with PHPStorm (new Composer Project).
