### ISSUE TITLE
Strange 'vboxmanage error failed to create host only adapter' messages while vagrant up

### ISSUE THREAD

**Issue by kermie** [OXID-eSales/oxvm_eshop#39]
I experienced some red-coloured error messages recently when running vagrant up from within my linux machine. Googled and found 
https://stackoverflow.com/questions/21069908/vboxmanage-error-failed-to-create-the-host-only-adapter

This might help: 
`sudo apt remove virtualbox virtualbox-5.1 virtualbox-5.0 virtualbox-4.*`

After that, execute this:
`sudo apt install virtualbox`

_vagrant up_ is running like a charme again, it's just about a virtualbox update ;)

**Comment by Sieg** [comment]
Hello @kermie, is the issue still valid? Is it related to the currently provided box solution? Looks like it was your personal setup upgrade problem?

**Comment by kermie** [comment]
Pls. close this issue - I can't even remember that case ;)
