### ISSUE TITLE
Unittests not possible in Windows 10

### ISSUE THREAD

**Issue by oxFilla** [OXID-eSales/oxvm_eshop#44]
After installation EE 6.1.5 and trying to run a ./vendor/bin/runtests the content of runtests is just printed two times.

I'm using vagrant on Windows 10. That effect exists also on another laptop too.

How can I make it run?

**Comment by Sieg** [comment]
Hello @oxid-filla,

First, you should ensure you have php installed on the system you want to run the tests on, so you could try calling it with php directly - like ``php ./vendor/bin/runtests``. But in any case, I would not guarantee it will work, as we have ["Linux"](https://docs.oxid-esales.com/eshop/en/6.1/installation/new-installation/server-and-system-requirements.html#web-server) requirement for the shop to be working.

Best what you can do - install the shop on our [Official OXID eShop VM](https://github.com/OXID-eSales/oxvm_eshop). Please read the readme how to start.

**Comment by oxid-filla** [comment]
The mentioned shops are running within the Official OXID eShop VM. That's why I made the issue in oxvm_eshop repo.

**Comment by keywan-ghadami** [comment]
that maybe related to virtual box/vagrant running without admin rights,
just a guess

oxid-filla <notifications@github.com> schrieb am Mi., 5. Feb. 2020, 10:24:

**Comment by Sieg** [comment]
Very strange, i should double check - are you trying to run the tests inside the vm? ;) but not directly on your pc, right?

The code can be displayed, in place of executing, if the system does not know how to deal with the php file.

**Comment by oxid-filla** [comment]
At least the shops inside the vms are running. So I would guess php is working.

And yes, tests runned inside the vm.

**Comment by Sieg** [comment]
Another double check - "Use console with Administrator privileges to run vagrant commands!", could you please remove the currently installed box and install the new one with this point?

**Comment by oxid-filla** [comment]
Same result.

**Comment by PirxDanford** [comment]
Hi @oxFilla can you please check if installing the shop in the /tmp directory and then copying it to /var/www/oxideshop similar as described here https://github.com/OXID-eSales/oxvm_eshop/issues/43#issuecomment-613471295 will resolve your issue?

**Comment by oxFilla** [comment]
I have tested it, but it does not solve the problem.

**Comment by PirxDanford** [comment]
Thanks to @zsolt-szilagyi for https://github.com/OXID-eSales/oxvm_eshop/pull/46 who is pointing out that using nfs now is a real option.

Please @oxFilla have a look at the "Start the VM (Solving Windows-specific symlink issues with a vagrant-plugin)" section in https://github.com/OXID-eSales/oxvm_eshop#quick-start hopefully this will solve the issue.

**Comment by Sieg** [comment]
Hey @oxFilla, could you please try out what's described in the last comment? Thanks!

**Comment by Sieg** [comment]
@oxFilla Feel free to reopen the issue if its still viable.
