### ISSUE TITLE
NFS for windows is not working as stated in README.rst with vagrant 2.2.13

### ISSUE THREAD

**Issue by BenjaminJoerger** [OXID-eSales/oxvm_eshop#48]
@zsolt-szilagyi 

https://www.vagrantup.com/docs/synced-folders/nfs
![console](https://user-images.githubusercontent.com/3601583/98917553-d1fed800-24cc-11eb-89ed-55fef72c02a4.png)

**Comment by zsolt-szilagyi** [comment]
Please verify that you have nfsd installed, as explained in the manual. If you have, please provide these informations:

- Exact OS version
- Vagrant version
- Oxid version

There is a remote chance that this approach requires the NFS client being installed. Please checkout https://graspingtech.com/mount-nfs-share-windows-10. If that's the solution, we can note it in the readme.
